default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: us_development

test:
  <<: *default
  database: us_test

production:
  <<: *default
  database: us_production
  username: root
  password: <%= ENV['US_DATABASE_PASSWORD'] %>
